name: Deploy documentation

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  docdeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: registry_add
        run: julia -e 'using Pkg; Pkg.Registry.add("General"); Pkg.Registry.add(RegistrySpec(url="https://github.com/LudwigBoess/LMBRegistry.git"))'
      - uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
